### ISSUE TITLE
working with three.js

### ISSUE THREAD

**Issue by rrmuduli** [DeborahK/Angular2-GettingStarted#23]
Dear Deborah,

I have watched your excellent tutorial from pluralsight - Angular2-GettingStarted. I am trying to integrate a three.js scene into a angular 2 page. I am a beginner in Angular, I have included the three.js file in the script tag, in index.html, i.e, <script src='node_modules/three-js/three.js'> and in the scene.component.ts file I have code like this...

//scene.component.ts
//
import { Component } from 'angular2/core';
import { THREE } from 'three-js/three';
@Component({
	selector: 'ps-scene',
	templateUrl: 'app/webgl/scene.component.html'
})
export class SceneComponent{
	scene = new THREE.Scene();
}

The problem is showing in the line - import { THREE } from 'three-js/three'; 

Can you please help. Thanks in advance.

Thanks and regards
rrmuduli

**Comment by DeborahK** [comment]
Thank you so much for the kind words about the course.
Regarding your question, you may have better luck posting to StackOverflow or gitter (https://gitter.im/). There you may find others that have used this same library.
Since this is not a direct issue with this sample code, I'm closing this issue.
Thanks again!
