### ISSUE TITLE
npm installing issue

### ISSUE THREAD

**Issue by YehualashetGit** [DeborahK/Angular2-GettingStarted#43]
typings WARN deprecated 11/21/2016: "registry:dt/node#6.0.0+20160831021119" is deprecated (updated, replaced or removed)
typings WARN deprecated 9/14/2016: "registry:dt/core-js#0.0.0+20160725163759" is deprecated (updated, replaced or removed)

├── core-js (global)
└── node (global)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

when I try to start the npm so give me response as soon as posible,my github account us YehualashetGit,or my email is yehuala5355@gmail.com

**Comment by DeborahK** [comment]
These are just warnings. I get the same thing. It should be able to then use 'npm start'

**Comment by YehualashetGit** [comment]
Ok Thank,another question,tell me  the learning path after finishing this
course ,getting started with angular 2,,and also tell me other work space
 rather than system js ,cause it showing many problem,last but not least
,is ,give me your advice how to master it for short period of time ,finally
,I would like to say ,I rely  like the way u teach ,I also take another
course i.e C# ,

**Comment by DeborahK** [comment]
Thank you for the kind words. 

Where to go next depends on your interest:
- Angular CLI if you want more info on that. (It uses WebPack instead of system.js)
- Angular 2 Reactive Forms if you want to learn about forms and http
- Angular Routing for more routing techniques, including lazy loading
- Angular 2 Fundamentals if you want more about everything

I'm closing this issue. If you have more questions, feel free to post to the discussion tab for the course here: 

https://app.pluralsight.com/library/courses/angular-2-getting-started-update/discussion

Thanks!
